### PR TITLE
Fixes flask errors where 402 is not a HTTP code

### PR DESCRIPTION
**Pull request by Tyler-Ward**

### CODE REVIEW

**Comment by Tyler-Ward** [comment]
From what myself and Mohit can tell Flask has removed error codes that are not standardized meaning mapping all error codes to our handler generates errors on any which don't exist.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward thanks! I'm happy to merge this ignoring the CI failure (which is unrelated).
I'm in the process of sorting out a formal licensing situation for this repo, ideally I'd like to go with something like MIT or BSD 3-Clause, though it's looking like we'll end up with GPLv3. Would you be ok with your contribution being under those licenses?

**Comment by Tyler-Ward** [comment]
MIT and BSD sound good to me.

**Comment by PeterJCLaw** [comment]
@Tyler-Ward thanks for your contribution though unfortunately as I think there's a strong likelihood we're going to need to license this under GPL (due to the preferences of one of the existing contributors) I don't think I'm going to be able to merge this.

**Pull request closed without merging**
